### ISSUE TITLE
Get Exception in thread "main" cvException when used another a Haar-based classifier. Edited DetectWithHaar Filter.

### ISSUE THREAD

**Issue by Aleksey-n** [hellonico/opencv-java-template#1]
Hello Nicolas!
### **DetectWithHaar class** **works fine**! 

> (with a Haar-based classifier _haarcascade_frontalface_default.xml_)

I'm trying to use another one classifier, for example https://github.com/opencv/opencv/blob/master/data/haarcascades/haarcascade_upperbody.xml or _*haarcascade_fullbody.xml_
and gets some errors like:
```
Exception in thread "main" CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.2.0) /home/pi/opencv4-native/opencv/modules/objdetect/src/cascadedetect.cpp:570: error: (-2:Unspecified error) in function 'bool cv::HaarEvaluator::Feature::read(const cv::FileNode&, const Size&)'
> Invalid HAAR feature (expected: 'rw.r.y + rw.r.height <=H'), where
>      'rw.r.y + rw.r.height' is 26
> must be less than or equal to
>     'H' is 14
]
```
**Can you please tell me what is the cause of the error and how it can be fixed?**

**Screenshot:**
![bugHaarCascade1](https://user-images.githubusercontent.com/33636228/94483463-5682e900-01f4-11eb-9e1c-196d3334443e.png)

**Comment by hellonico** [comment]
hi there ! 
how did u load the classifier ? could you show the code ?

**Comment by hellonico** [comment]
Here is a full example:

```
package hello;

import static org.opencv.imgcodecs.Imgcodecs.imread;
import static org.opencv.imgcodecs.Imgcodecs.imwrite;

import java.io.InputStream;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;

import org.opencv.core.Mat;
import org.opencv.core.MatOfRect;
import org.opencv.core.Point;
import org.opencv.core.Rect;
import org.opencv.core.Scalar;
import org.opencv.imgproc.Imgproc;
import org.opencv.objdetect.CascadeClassifier;

import origami.Origami;

public class HelloClassifier {

    public static void main(String[] args) throws Exception {
        Origami.init();
        String classifierUrl = "https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_upperbody.xml";
        String classifierPath = "haarcascade_upperbody.xml";
        download(classifierUrl, classifierPath);
        String imageUrl = "https://www.netclipart.com/pp/m/106-1066497_suit-man-png-man-in-suit-png.png";
        download(imageUrl, "men.jpg");
        CascadeClassifier classifier = new CascadeClassifier();
        classifier.load(classifierPath);
        Mat mat = imread("men.jpg");
        MatOfRect bodies = new MatOfRect();
        classifier.detectMultiScale(mat, bodies);
        System.out.println(bodies.toList());
        for (Rect body : bodies.toList()) {
            Imgproc.rectangle(mat, new Point(body.x, body.y), new Point(body.x + body.width, body.y + body.height),
                    new Scalar(0, 100, 0), 3);
        }
        imwrite("output.jpg", mat);

    }

    static void download(String url, String name) throws Exception {
        InputStream in = new URL(url).openStream();
        Files.copy(in, Paths.get(name), StandardCopyOption.REPLACE_EXISTING);
    }

}
```

**Comment by hellonico** [comment]
I have added the java code here:

https://github.com/hellonico/opencv4_java_tutorial/blob/7e936b22a3586a4b046c645c943dace032af270c/java/me/BodyClassifier.java

Let me know if that works for you.

**Comment by Aleksey-n** [comment]
**Thank you for good example!**

There's solution to this problem. 
I'm changed source for haar
From
`Filter haar = new Haar("/home/pi/code/opencv/data/haarcascades_cuda/haarcascade_upperbody.xml"); //upperbody`
To
`Filter haar = new Haar("haarcascade_upperbody.xml");`

![UpperBodyOutput_1](https://user-images.githubusercontent.com/33636228/94982713-5d905b00-0556-11eb-871b-d8fcf5257cef.png)
![UpperBodyOutput1](https://user-images.githubusercontent.com/33636228/94982724-5f5a1e80-0556-11eb-951c-9949873c5c1e.png)

_got 2 fps, i think need more testing for increase this_

**Comment by Aleksey-n** [comment]
new haar xml was downloaded from https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_upperbody.xml

**Comment by hellonico** [comment]
Nice ! Works real time on your pi right ?

**Comment by Aleksey-n** [comment]
Yep :) RPi 3 Model B

Not satisfied with **the number of frames per second** & **recognition quality 7/10** ... tried to change the settings, some variations of:
classifier.detectMultiScale(input, faces, 1.01, 1, -1, new Size(100, 100), new Size(320, 320));
still low recognition quality

_"Seven party faces"_ is not enough (7/10) 

Why did you choose OpenCV?

**Comment by hellonico** [comment]
You could try a Rpi4 ... Rpi3 did not get much better than this. 

I am usually using OpenCV with DNN networks (mostly darknet). 

OpenCV was the easiest to hack with and I got pretty good speed, at least 10~15 fps and more if I reduce the image file size.
