### ISSUE TITLE
The constructor VideoCapture(String) is undefined  Real-Time IoT Imaging with Deep Neural Networks

### ISSUE THREAD

**Issue by SirCarlitros** [hellonico/opencv-java-template#3]
Hi, i am trying to test the activities of your book "Real-Time IoT Imaging with Deep Neural Networks - Using Java on the Raspberry Pi 4" when i run the java file with name PlayVideo.java in the line where I instantiate a VideoCapture object VSCode show the next error:

![Code](https://user-images.githubusercontent.com/46206235/103451949-d4410f80-4c8f-11eb-8122-b7e73f5c0aae.jpg)

Windows 10
I use VSCODE 1.52.1
JDK 15.0 (I tried with JDK 1.8 and JDK 13.1  )
The version of the opencv in the jar Files is the 4.3.0-0.jar and the version of native opencv is 4.3.0-1 (I dont know if it could be the cause of the error)
I renamed a video file with the name "marcel_1.mp4" but didnt work.

Thank for your attention

**Comment by hellonico** [comment]
Really sorry ! I am just seeing this now ~ 
The OpenCV API changed, in the meantime you can use this:

```
VideoCapture vc = new VideoCapture();
vc.open("marcel_1.mp4");
```
